# Generated by Django 2.2.3 on 2019-07-17 03:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circle',
            name='circle_name',
        ),
        migrations.AlterUniqueTogether(
            name='circleuser',
            unique_together={('user', 'circle')},
        ),
    ]
